# Export findings as SARIF and upload to GitHub Code Scanning (Security tab).
name: IAM Policy Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Scan IAM policies
        uses: boogy/iam-policy-auditor@v1
        continue-on-error: true # don't block the SARIF upload
        with:
          path: policies/
          format: sarif
          output-file: iam-results.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: iam-results.sarif
          category: iam-policy-validation
