# Only validate IAM policies that were actually changed in the PR.
# Useful for repos where policies aren't in a dedicated directory.
# The action auto-filters non-IAM files (configs, schemas, etc.).
name: Validate Changed IAM Policies

on:
  pull_request:
    paths:
      - "**/*.json"
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **/*.json
            **/*.yaml
            **/*.yml

      - name: Validate changed IAM policies
        if: steps.changed.outputs.any_changed == 'true'
        uses: boogy/iam-policy-auditor@v1
        with:
          path: ${{ steps.changed.outputs.all_changed_files }}
          post-comment: true
          create-review: true
          fail-on-warnings: true
