# Validate Only Changed IAM Policies
# Automatically detects IAM policies from all changed JSON/YAML files in PR
# Filters out non-IAM files (configs, data files, schemas, etc.)

name: Validate Changed IAM Policies

on:
  pull_request:
    paths:
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  validate-changed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0  # Fetch all history for changed files detection

      - name: Get changed JSON/YAML files
        id: changed-files
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 # v45.0.4
        with:
          files: |
            **/*.json
            **/*.yaml
            **/*.yml

      - name: List changed files
        run: |
          echo "📝 Changed JSON/YAML files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Validate IAM Policies from Changed Files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: boogy/iam-policy-validator@v1
        with:
          # Pass all changed JSON/YAML files
          # Action automatically filters to only IAM policies
          path: ${{ steps.changed-files.outputs.all_changed_files }}
          post-comment: true
          create-review: true
          fail-on-warnings: true

      - name: No files changed
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "ℹ️  No JSON/YAML files changed in this PR"
