name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0 # Full history for changelog generation

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@5dbc9fba7434435c4cd0268139340fa3696d98f3 # v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            # First release - get all commits
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            # Get commits since previous tag
            CHANGELOG=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Save to file for multiline output
          echo "$CHANGELOG" > CHANGELOG.txt

          # Also create a summary
          COMMIT_COUNT=$(echo "$CHANGELOG" | wc -l)
          echo "Generated changelog with $COMMIT_COUNT commits"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2
        with:
          name: ${{ steps.get_version.outputs.tag }}
          body_path: CHANGELOG.txt
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, 'rc') || contains(steps.get_version.outputs.version, 'beta') || contains(steps.get_version.outputs.version, 'alpha') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        if: |
          !contains(steps.get_version.outputs.version, 'rc') &&
          !contains(steps.get_version.outputs.version, 'beta') &&
          !contains(steps.get_version.outputs.version, 'alpha')
        run: uv publish --trusted-publishing always

      - name: Create Release Summary
        if: always()
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="${{ steps.get_version.outputs.tag }}"
          IS_PRERELEASE="${{ contains(steps.get_version.outputs.version, 'rc') || contains(steps.get_version.outputs.version, 'beta') || contains(steps.get_version.outputs.version, 'alpha') }}"

          # Extract major and minor versions
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f1-2)

          cat >> $GITHUB_STEP_SUMMARY << EOF
          # 🚀 Release Summary

          ## 📦 Package Information
          - **Package**: \`iam-policy-validator\`
          - **Version**: \`$VERSION\`
          - **Tag**: \`$TAG\`

          ## 📋 What Was Published

          ### GitHub Release
          - ✅ Created release: [$TAG](https://github.com/${{ github.repository }}/releases/tag/$TAG)
          - 📄 Changelog generated from commits
          - 📦 Artifacts attached: wheel + source distribution

          ### PyPI
          $(if [ "$IS_PRERELEASE" = "false" ]; then echo "- ✅ Published to [PyPI](https://pypi.org/project/iam-policy-validator/)"; else echo "- ⏭️ Skipped (pre-release version)"; fi)

          ### Version Tags
          - 🏷️ Major tag: \`v$MAJOR\`
          - 🏷️ Minor tag: \`v$MINOR\`
          - 🏷️ Full tag: \`v$VERSION\`

          ## 🔗 Quick Links
          - [📦 PyPI Package](https://pypi.org/project/iam-policy-validator/)
          - [📚 GitHub Release](https://github.com/${{ github.repository }}/releases/tag/$TAG)
          - [📖 Repository](https://github.com/${{ github.repository }})

          ## 📥 Installation
          \`\`\`bash
          pip install iam-policy-validator==$VERSION
          \`\`\`

          or use the latest:
          \`\`\`bash
          pip install iam-policy-validator
          \`\`\`
          EOF

  update-action-versions:
    name: Update Major/Minor Tag References
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update major and minor version tags
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f1-2)

          # Update vX tag (e.g., v1) - annotated (unsigned by bot)
          git tag -fa "v$MAJOR" -m "Update v$MAJOR to $VERSION"
          git push origin "v$MAJOR" --force

          # Update vX.Y tag (e.g., v1.2) - annotated (unsigned by bot)
          git tag -fa "v$MINOR" -m "Updated v$MINOR to $VERSION"
          git push origin "v$MINOR" --force

          echo "✅ Updated tags: v$MAJOR and v$MINOR to point to $VERSION"
          echo "ℹ️  Note: Automated tags are annotated but not signed by the bot."
