name: Validate IAM Policies

on:
  pull_request:
    paths:
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'
      - 'policies/**'
      - 'iam-policies/**'

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  validate-policies:
    name: Validate IAM Policies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for diff

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.json
            **/*.yaml
            **/*.yml
          files_ignore: |
            package*.json
            tsconfig.json
            .github/**
            .vscode/**

      - name: Validate IAM Policies
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./
        with:
          path: ${{ steps.changed-files.outputs.all_changed_files }}
          fail-on-warnings: true
          post-comment: true
          create-review: true

      - name: Post summary
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "## IAM Policy Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Validation completed. Check the PR comments for details." >> $GITHUB_STEP_SUMMARY